using System.Text.Json;
using System.Text.Json.Serialization;

namespace MorpheusEngine;

// Note: sealing private records is the desired default: it doesn't change affect the open-closed principle while ruling out some potential autogenerated equality comparator bugs.

/// <summary>Thrown when engine_config.json is missing, invalid, or violates the engine contract (fail fast; no silent fallbacks).</summary>
public sealed class EngineConfigurationException : Exception
{
    public EngineConfigurationException(string message)
        : base(message)
    {
    }

    public EngineConfigurationException(string message, Exception innerException)
        : base(message, innerException)
    {
    }
}

/// <summary>Maps each module port_key to its TCP listen port.</summary>
public sealed class EnginePortMap
{
    private readonly IReadOnlyDictionary<string, int> _mapping; // Port identifier to int: example: "router" -> 1234

    // Constructor restricted to this project only.
    internal EnginePortMap(IReadOnlyDictionary<string, int> mapping)
    {
        _mapping = mapping;
    }

    /// <summary>Returns the configured listen port for a known module <paramref name="portKey"/>.</summary>
    /// <exception cref="EngineConfigurationException">Unknown <paramref name="portKey"/>.</exception>
    public int GetRequiredPort(string portKey) // portKey example: "router", resolves to int.
    {
        if (!_mapping.TryGetValue(portKey, out var port))
        {
            throw new EngineConfigurationException(
                $"Unknown port_key '{portKey}' for listen port lookup. Known keys: {string.Join(", ", _mapping.Keys)}.");
        }

        return port;
    }

    /// <summary>Whether <paramref name="portKey"/> has a listen port entry (used when validating module rows).</summary>
    public bool HasListenPortForModule(string portKey) => _mapping.ContainsKey(portKey);
}

/// <summary>Launch metadata for a module process.</summary>
/// <param name="Artifact">Path to the built executable (often under bin/Debug/...), relative to the repository root unless absolute.</param>
public sealed record EngineModuleLaunchInfo(string Artifact);

/// <summary>One HTTP endpoint exposed by a module.</summary>
/// <param name="Path">URL path on that module, e.g. /health or /intent.</param>
/// <param name="Description">Short label; used by the WPF UI when listing endpoints (see MainWindow).</param>
/// <param name="Method">GET or POST (required in JSON).</param>
/// <param name="TemplateContractsId">Logical template id that maps to example request/response bodies (used by tooling/UI).</param>
/// <param name="RequestBodyTemplate">Optional JSON request body template (POST only). If omitted, filled via <see cref="EngineContractExamples"/>.</param>
/// <param name="ResponseBodyTemplate">Optional JSON response body template. If omitted, filled via <see cref="EngineContractExamples"/>.</param>
public sealed record EngineEndpointInfo(
    string Path, // example: /health, /intent
    string? Description, // Used by MainWindow for combo box / endpoint labels.
    string Method,
    string? TemplateContractsId, // Logical template id for request+response JSON examples.
    string? RequestBodyTemplate,
    string? ResponseBodyTemplate);

public sealed record EngineTurnPipelineStepInfo(
    string Id,
    string TargetModule,
    string Path,
    string Method,
    string BodyTemplate,
    bool ContinueOnFailure = false);

public sealed record EngineTurnPipelineResponseMapping(
    string SourceStep,
    string Type);

public sealed record EngineTurnPipelineInfo(
    string Id,
    IReadOnlyList<EngineTurnPipelineStepInfo> Steps,
    EngineTurnPipelineResponseMapping ResponseMapping);

/// <summary>Options required by whichever concrete module is mapped from generic_llm_provider.</summary>
public sealed record GenericLlmProviderModuleOptions(
    int NumCtx);

/// <summary>Options specific to the llm_provider_qwen module implementation.</summary>
public sealed record QwenModuleOptions(
    int OllamaPort,
    string OllamaModel);

/// <summary>Options specific to the memory_director module implementation.</summary>
public sealed record MemoryDirectorModuleOptions(
    int MaxStepsPerTurn,
    int MaxToolResultChars,
    int MaxFullMessages,
    string KeepAlive);

/// <summary>Options specific to the Ollama-backed embeddings module implementation.</summary>
public sealed record EmbeddingsModuleOptions(
    int OllamaPort,
    string DefaultEmbeddingModel,
    string KeepAlive,
    int NumCtx);

public sealed record EngineModuleInfo(
    string PortKey, // stable module id (e.g. router); actual port is in EngineConfiguration.PortMap.
    string DisplayName, // Shown in UI / logs;
    bool RequiredByEngine,
    int LoadOrder,
    EngineModuleLaunchInfo LaunchInfo,
    IReadOnlyList<EngineEndpointInfo> Endpoints,
    /// <summary>Set only on the module resolved from generic_llm_provider.</summary>
    GenericLlmProviderModuleOptions? GenericLlmProviderOptions = null,
    /// <summary>Set only on llm_provider_qwen.</summary>
    QwenModuleOptions? QwenOptions = null,
    /// <summary>Set only on memory_director.</summary>
    MemoryDirectorModuleOptions? MemoryDirectorOptions = null,
    /// <summary>Set only on the module resolved from generic_embeddings.</summary>
    EmbeddingsModuleOptions? EmbeddingsOptions = null);

/// <summary>Loaded engine configuration: repository layout, listen ports, module list, and proxy aliases. Provider-specific options live on each <see cref="EngineModuleInfo"/> row.</summary>
public sealed class EngineConfiguration
{
    /// <summary>Repository root containing engine_config.json and typically a dotnet folder.</summary>
    // Q: what's this used for? — Resolving relative artifact paths and choosing the dotnet working directory.
    public string RepositoryRoot { get; }

    public EnginePortMap PortMap { get; }

    public IReadOnlyList<EngineModuleInfo> ModulesInfos { get; }

    public IReadOnlyDictionary<string, EngineTurnPipelineInfo> TurnPipelines { get; }

    // Used to make http messages mention only the generic modules instead of having to rely on specific implementation modules. Ex: llm_provider_qwen becomes just generic_llm_provider and the Router resolves it back to llm_provider_qwen or whichever generic llm module is currently used.
    public IReadOnlyDictionary<string, string> ModuleAliases { get; }

    public EngineConfiguration(
        string repositoryRoot,
        EnginePortMap portMap,
        IReadOnlyList<EngineModuleInfo> modulesInfos,
        IReadOnlyDictionary<string, string> moduleAliases,
        IReadOnlyDictionary<string, EngineTurnPipelineInfo> turnPipelines)
    {
        RepositoryRoot = repositoryRoot;
        PortMap = portMap;
        ModulesInfos = modulesInfos;
        ModuleAliases = moduleAliases;
        TurnPipelines = turnPipelines;
    }

    /// <summary>Concrete <see cref="EngineModuleInfo"/> row for the module named by <c>generic_llm_provider</c> in <see cref="ModuleAliases"/>.</summary>
    public EngineModuleInfo GetRequiredGenericLlmProviderModule()
    {
        var key = ResolveProxyTargetModuleKey("generic_llm_provider");
        return FindModule(key)
            ?? throw new EngineConfigurationException(
                $"Configured modules do not include port_key '{key}' (generic_llm_provider alias target).");
    }

    /// <summary>Concrete <see cref="EngineModuleInfo"/> row for the module named by generic_director in <see cref="ModuleAliases"/>.</summary>
    public EngineModuleInfo GetRequiredGenericDirectorModule()
    {
        var key = ResolveProxyTargetModuleKey("generic_director");
        return FindModule(key)
            ?? throw new EngineConfigurationException(
                $"Configured modules do not include port_key '{key}' (generic_director alias target).");
    }

    /// <summary>Concrete <see cref="EngineModuleInfo"/> row for the module named by generic_embeddings in <see cref="ModuleAliases"/>.</summary>
    public EngineModuleInfo GetRequiredGenericEmbeddingsModule()
    {
        var key = ResolveProxyTargetModuleKey("generic_embeddings");
        return FindModule(key)
            ?? throw new EngineConfigurationException(
                $"Configured modules do not include port_key '{key}' (generic_embeddings alias target).");
    }

    /// <summary>
    /// Resolves a logical proxy target (e.g. generic_llm_provider) to a configured port_key before module lookup.
    /// Keys that are already real port_key values pass through unchanged (not an error—no log spam).
    /// </summary>
    public string ResolveProxyTargetModuleKey(string logicalKey)
    {
        if (string.IsNullOrWhiteSpace(logicalKey))
        {
            return logicalKey;
        }

        return ModuleAliases.TryGetValue(logicalKey, out var mapped) && !string.IsNullOrWhiteSpace(mapped)
            ? mapped.Trim()
            : logicalKey;
    }

    /// <inheritdoc cref="EnginePortMap.GetRequiredPort"/>
    public int GetRequiredListenPort(string portKey)
    {
        var resolved = ResolveProxyTargetModuleKey(portKey);
        return PortMap.GetRequiredPort(resolved);
    }

    /// <summary>
    /// Prefer this over a property: path is derived from <see cref="RepositoryRoot"/> and directory existence.
    /// Example: repository C:\MorpheusEngine with a dotnet subfolder → C:\MorpheusEngine\dotnet;
    /// if dotnet is missing (non-standard layout) → falls back to <see cref="RepositoryRoot"/>.
    /// </summary>
    // Q: in what conditions would dotnetRoot not exist? — Sparse checkouts or running with config at repo root without a dotnet subdir.
    public string GetDotnetRoot()
    {
        var dotnetRoot = Path.Combine(RepositoryRoot, "dotnet");
        return Directory.Exists(dotnetRoot) ? dotnetRoot : RepositoryRoot;
    }

    public EngineModuleInfo? FindModule(string portKey)
    {
        foreach (var module in ModulesInfos)
        {
            if (string.Equals(module.PortKey, portKey, StringComparison.OrdinalIgnoreCase))
            {
                return module;
            }
        }

        return null;
    }

    public EngineTurnPipelineInfo GetRequiredTurnPipeline(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
        {
            throw new EngineConfigurationException("turn_pipeline id must be non-empty.");
        }

        return TurnPipelines.TryGetValue(id.Trim(), out var pipeline)
            ? pipeline
            : throw new EngineConfigurationException(
                $"Unknown turn_pipeline '{id}'. Known pipelines: {string.Join(", ", TurnPipelines.Keys.OrderBy(static key => key, StringComparer.OrdinalIgnoreCase))}.");
    }

    /// <summary>Finds which module is bound to the given TCP <paramref name="port"/> (listen ports from <see cref="PortMap"/>).</summary>
    public EngineModuleInfo? GetModuleForListeningPort(int port)
    {
        foreach (var module in ModulesInfos)
        {
            if (GetRequiredListenPort(module.PortKey) == port)
            {
                return module;
            }
        }

        return null;
    }

    public EngineEndpointInfo? FindEndpointForPort(int port, string path)
    {
        var normalized = NormalizePath(path);
        var module = GetModuleForListeningPort(port);
        if (module is null)
        {
            return null; // Acceptable to return null in this case: indicates failure to find endpoint.
        }

        foreach (var endpoint in module.Endpoints)
        {
            if (string.Equals(NormalizePath(endpoint.Path), normalized, StringComparison.OrdinalIgnoreCase))
            {
                return endpoint;
            }
        }

        return null;
    }

    public static string NormalizePath(string path)
    {
        if (string.IsNullOrWhiteSpace(path))
        {
            return "/";
        }

        var trimmed = path.Trim();
        return trimmed.StartsWith('/') ? trimmed : "/" + trimmed;
    }
}

// Note: public static class in C# forces a singleton like behaviour.
public static class EngineConfigLoader
{
    #region Nested types
    // DTO: Data transfer object: JSON deserialization shape, not the runtime EngineConfiguration model.

    private sealed class EngineConfigFileDto
    {
        public List<ModuleDto>? Modules { get; set; }

        [JsonPropertyName("module_aliases")]
        public Dictionary<string, string>? ModuleAliases { get; set; }

        [JsonPropertyName("turn_pipelines")]
        public Dictionary<string, TurnPipelineDto>? TurnPipelines { get; set; }
    }

    private sealed class TurnPipelineDto
    {
        public List<TurnPipelineStepDto>? Steps { get; set; }

        [JsonPropertyName("response_mapping")]
        public TurnPipelineResponseMappingDto? ResponseMapping { get; set; }
    }

    private sealed class TurnPipelineStepDto
    {
        public string? Id { get; set; }

        [JsonPropertyName("target_module")]
        public string? TargetModule { get; set; }

        public string? Path { get; set; }
        public string? Method { get; set; }

        [JsonPropertyName("body_template")]
        public string? BodyTemplate { get; set; }

        [JsonPropertyName("continue_on_failure")]
        public bool? ContinueOnFailure { get; set; }
    }

    private sealed class TurnPipelineResponseMappingDto
    {
        [JsonPropertyName("source_step")]
        public string? SourceStep { get; set; }

        public string? Type { get; set; }
    }

    private sealed class ModuleDto
    {
        [JsonPropertyName("port_key")]
        public string? PortKey { get; set; }

        public int? Port { get; set; }

        [JsonPropertyName("load_order")]
        public int? LoadOrder { get; set; }

        [JsonPropertyName("display_name")]
        public string? DisplayName { get; set; }

        [JsonPropertyName("required_by_engine")]
        public bool? RequiredByEngine { get; set; }
        public string? Launch { get; set; }
        public List<EndpointDto>? Endpoints { get; set; }

        [JsonPropertyName("ollama_port")]
        public int? OllamaPort { get; set; }

        [JsonPropertyName("default_chat_model")]
        public string? OllamaModel { get; set; }

        [JsonPropertyName("default_embedding_model")]
        public string? DefaultEmbeddingModel { get; set; }

        [JsonPropertyName("num_ctx")]
        public int? NumCtx { get; set; }

        [JsonPropertyName("embeddings_num_ctx")]
        public int? EmbeddingsNumCtx { get; set; }

        [JsonPropertyName("max_steps_per_turn")]
        public int? MaxStepsPerTurn { get; set; }

        [JsonPropertyName("max_tool_result_chars")]
        public int? MaxToolResultChars { get; set; }

        [JsonPropertyName("max_full_messages")]
        public int? MaxFullMessages { get; set; }

        [JsonPropertyName("keep_model_loaded_for")]
        public string? KeepAlive { get; set; }
    }

    private sealed class EndpointDto
    {
        // Q: why no JsonPropertyName()'s here? — Names match JSON camelCase defaults with PropertyNameCaseInsensitive on serializer.
        public string? Path { get; set; }
        public string? Description { get; set; }
        public string? Method { get; set; }

        [JsonPropertyName("template_contracts_id")]
        public string? TemplateContractsId { get; set; }

        [JsonPropertyName("request_body_template")]
        public string? RequestBodyTemplate { get; set; }

        [JsonPropertyName("response_body_template")]
        public string? ResponseBodyTemplate { get; set; }
    }
    #endregion

    #region Private data
    private static readonly JsonSerializerOptions _jsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        ReadCommentHandling = JsonCommentHandling.Skip,
        AllowTrailingCommas = true
    };

    private static EngineConfiguration? _cached;

    /// <summary>Protects double-checked initialization of <see cref="_cached"/> together with <see cref="GetConfiguration"/>.</summary>
    // Mutex for the cache: only one thread runs <see cref="LoadConfigurationUncached"/> when cache is cold.
    private static readonly object Sync = new();
    #endregion

    #region Public methods
    public static EngineConfiguration GetConfiguration()
    {
        EngineConfiguration LoadConfigurationUncached()
        {
            static IReadOnlyDictionary<string, string> MergeModuleAliases(Dictionary<string, string>? fromFile, string path)
            {
                if (fromFile is null)
                {
                    throw new EngineConfigurationException($"engine_config.json at '{path}' must contain a top-level 'module_aliases' object.");
                }

                var merged = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                foreach (var pair in fromFile)
                {
                    if (string.IsNullOrWhiteSpace(pair.Key) || string.IsNullOrWhiteSpace(pair.Value))
                    {
                        throw new EngineConfigurationException(
                            $"module_aliases in '{path}' contains an entry with empty key or value.");
                    }

                    merged[pair.Key.Trim()] = pair.Value.Trim();
                }

                return merged;
            }

            static string ResolveRequiredGenericProviderModuleKey(
                IReadOnlyDictionary<string, string> moduleAliases,
                string path)
            {
                if (!moduleAliases.TryGetValue("generic_llm_provider", out var mapped) || string.IsNullOrWhiteSpace(mapped))
                {
                    throw new EngineConfigurationException(
                        $"module_aliases in '{path}' must map 'generic_llm_provider' to a concrete module key.");
                }

                return mapped.Trim();
            }

            static string ResolveRequiredGenericDirectorModuleKey(
                IReadOnlyDictionary<string, string> moduleAliases,
                string path)
            {
                if (!moduleAliases.TryGetValue("generic_director", out var mapped) || string.IsNullOrWhiteSpace(mapped))
                {
                    throw new EngineConfigurationException(
                        $"module_aliases in '{path}' must map 'generic_director' to a concrete module key.");
                }

                return mapped.Trim();
            }

            static string ResolveRequiredGenericEmbeddingsModuleKey(
                IReadOnlyDictionary<string, string> moduleAliases,
                string path)
            {
                if (!moduleAliases.TryGetValue("generic_embeddings", out var mapped) || string.IsNullOrWhiteSpace(mapped))
                {
                    throw new EngineConfigurationException(
                        $"module_aliases in '{path}' must map 'generic_embeddings' to a concrete module key.");
                }

                return mapped.Trim();
            }

            static EnginePortMap BuildPortMapFromModules(IReadOnlyList<ModuleDto> modules, string configPath)
            {
                if (modules.Count == 0)
                {
                    throw new EngineConfigurationException($"engine_config.json at '{configPath}' must contain a non-empty 'modules' array.");
                }

                var dict = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
                var seenPorts = new HashSet<int>();
                foreach (var module in modules)
                {
                    var key = module.PortKey?.Trim();
                    if (string.IsNullOrWhiteSpace(key))
                    {
                        throw new EngineConfigurationException(
                            $"modules[] entry in '{configPath}' is missing port_key (required to build the port map).");
                    }

                    if (module.Port is null)
                    {
                        throw new EngineConfigurationException(
                            $"Module '{key}' in '{configPath}' is missing port (each module must declare its own listen port).");
                    }

                    var port = module.Port.Value;
                    if (port is < 1 or > 65535)
                    {
                        throw new EngineConfigurationException($"Module '{key}' port in '{configPath}' must be between 1 and 65535 (got {port}).");
                    }

                    if (!seenPorts.Add(port))
                    {
                        throw new EngineConfigurationException($"Duplicate listen port {port} in '{configPath}' (each module must have a unique port).");
                    }

                    dict[key] = port;
                }

                return new EnginePortMap(dict);
            }

            static IReadOnlyList<EngineEndpointInfo> MergeEndpoints(List<EndpointDto>? endpointsDto, string modulePortKey, string path)
            {
                if (endpointsDto is null)
                {
                    throw new EngineConfigurationException($"Module '{modulePortKey}' in '{path}' must declare an endpoints array.");
                }

                var list = new List<EngineEndpointInfo>();
                foreach (var endpoint in endpointsDto)
                {
                    var epPath = endpoint.Path?.Trim();
                    if (string.IsNullOrEmpty(epPath))
                    {
                        throw new EngineConfigurationException(
                            $"Module '{modulePortKey}' in '{path}' has an endpoint with missing or empty path.");
                    }

                    if (string.IsNullOrWhiteSpace(endpoint.Method))
                    {
                        throw new EngineConfigurationException(
                            $"Module '{modulePortKey}' endpoint '{epPath}' in '{path}' must declare method (GET or POST).");
                    }

                    var method = endpoint.Method.Trim().ToUpperInvariant();
                    if (method is not ("GET" or "POST"))
                    {
                        throw new EngineConfigurationException(
                            $"Module '{modulePortKey}' endpoint '{epPath}' in '{path}' has invalid method '{endpoint.Method}' (expected GET or POST).");
                    }

                    var templateContractsId = string.IsNullOrWhiteSpace(endpoint.TemplateContractsId)
                        ? null
                        : endpoint.TemplateContractsId.Trim();

                    var templates = EngineContractExamples.TryGetTemplates(templateContractsId);
                    var requestBodyTemplate = string.IsNullOrWhiteSpace(endpoint.RequestBodyTemplate)
                        ? templates?.RequestBodyTemplate
                        : endpoint.RequestBodyTemplate;
                    var responseBodyTemplate = string.IsNullOrWhiteSpace(endpoint.ResponseBodyTemplate)
                        ? templates?.ResponseBodyTemplate
                        : endpoint.ResponseBodyTemplate;

                    list.Add(new EngineEndpointInfo(
                        EngineConfiguration.NormalizePath(epPath),
                        string.IsNullOrWhiteSpace(endpoint.Description) ? null : endpoint.Description.Trim(),
                        method,
                        templateContractsId,
                        requestBodyTemplate,
                        responseBodyTemplate));
                }

                return list;
            }

            static IReadOnlyDictionary<string, EngineTurnPipelineInfo> MergeTurnPipelines(
                Dictionary<string, TurnPipelineDto>? pipelinesDto,
                string path)
            {
                if (pipelinesDto is null || pipelinesDto.Count == 0)
                {
                    throw new EngineConfigurationException($"engine_config.json at '{path}' must define non-empty turn_pipelines.");
                }

                var pipelines = new Dictionary<string, EngineTurnPipelineInfo>(StringComparer.OrdinalIgnoreCase);
                foreach (var pair in pipelinesDto)
                {
                    var id = pair.Key.Trim();
                    if (string.IsNullOrWhiteSpace(id))
                    {
                        throw new EngineConfigurationException($"turn_pipelines in '{path}' contains an empty pipeline id.");
                    }

                    var dto = pair.Value ?? throw new EngineConfigurationException($"turn_pipelines.{id} in '{path}' must be an object.");
                    if (dto.Steps is null || dto.Steps.Count == 0)
                    {
                        throw new EngineConfigurationException($"turn_pipelines.{id} in '{path}' must define a non-empty steps array.");
                    }

                    var steps = new List<EngineTurnPipelineStepInfo>();
                    var stepIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                    foreach (var stepDto in dto.Steps)
                    {
                        var stepId = stepDto.Id?.Trim();
                        if (string.IsNullOrWhiteSpace(stepId) || !stepIds.Add(stepId))
                        {
                            throw new EngineConfigurationException($"turn_pipelines.{id} in '{path}' has an empty or duplicate step id.");
                        }

                        if (string.IsNullOrWhiteSpace(stepDto.TargetModule))
                        {
                            throw new EngineConfigurationException($"turn_pipelines.{id}.{stepId} in '{path}' must define target_module.");
                        }

                        if (string.IsNullOrWhiteSpace(stepDto.Path))
                        {
                            throw new EngineConfigurationException($"turn_pipelines.{id}.{stepId} in '{path}' must define path.");
                        }

                        if (string.IsNullOrWhiteSpace(stepDto.BodyTemplate))
                        {
                            throw new EngineConfigurationException($"turn_pipelines.{id}.{stepId} in '{path}' must define body_template.");
                        }

                        var method = stepDto.Method?.Trim().ToUpperInvariant();
                        if (method is not ("GET" or "POST"))
                        {
                            throw new EngineConfigurationException($"turn_pipelines.{id}.{stepId} in '{path}' must use method GET or POST.");
                        }

                        steps.Add(new EngineTurnPipelineStepInfo(
                            stepId,
                            stepDto.TargetModule.Trim(),
                            EngineConfiguration.NormalizePath(stepDto.Path),
                            method,
                            stepDto.BodyTemplate,
                            stepDto.ContinueOnFailure ?? false));
                    }

                    var mapping = dto.ResponseMapping
                        ?? throw new EngineConfigurationException($"turn_pipelines.{id} in '{path}' must define response_mapping.");
                    var sourceStep = mapping.SourceStep?.Trim();
                    if (string.IsNullOrWhiteSpace(sourceStep) || !stepIds.Contains(sourceStep))
                    {
                        throw new EngineConfigurationException($"turn_pipelines.{id}.response_mapping.source_step in '{path}' must reference an existing step id.");
                    }

                    var type = mapping.Type?.Trim();
                    if (type is not "director_message_response")
                    {
                        throw new EngineConfigurationException($"turn_pipelines.{id}.response_mapping.type in '{path}' must be 'director_message_response'.");
                    }

                    pipelines[id] = new EngineTurnPipelineInfo(id, steps, new EngineTurnPipelineResponseMapping(sourceStep, type));
                }

                return pipelines;
            }

            static void ValidateTurnPipelines(
                IReadOnlyDictionary<string, EngineTurnPipelineInfo> pipelines,
                IReadOnlyList<EngineModuleInfo> modules,
                IReadOnlyDictionary<string, string> moduleAliases,
                string path)
            {
                foreach (var pipeline in pipelines.Values)
                {
                    foreach (var step in pipeline.Steps)
                    {
                        var resolved = moduleAliases.TryGetValue(step.TargetModule, out var mapped) && !string.IsNullOrWhiteSpace(mapped)
                            ? mapped.Trim()
                            : step.TargetModule;
                        var module = modules.FirstOrDefault(module =>
                            string.Equals(module.PortKey, resolved, StringComparison.OrdinalIgnoreCase));
                        if (module is null)
                        {
                            throw new EngineConfigurationException(
                                $"turn_pipelines.{pipeline.Id}.{step.Id} in '{path}' targets unknown module or alias '{step.TargetModule}'.");
                        }

                        var endpoint = module.Endpoints.FirstOrDefault(endpoint =>
                            string.Equals(EngineConfiguration.NormalizePath(endpoint.Path), EngineConfiguration.NormalizePath(step.Path), StringComparison.OrdinalIgnoreCase)
                            && string.Equals(endpoint.Method, step.Method, StringComparison.OrdinalIgnoreCase));
                        if (endpoint is null)
                        {
                            throw new EngineConfigurationException(
                                $"turn_pipelines.{pipeline.Id}.{step.Id} in '{path}' targets {step.Method} {step.Path}, which is not allowlisted on module '{module.PortKey}'.");
                        }
                    }
                }
            }

            static void ValidateModuleScopedOptions(
                string portKey,
                bool isActiveGenericProvider,
                bool isQwen,
                bool isMemoryDirector,
                bool isActiveGenericEmbeddings,
                int? ollamaPort,
                string? ollamaModel,
                string? defaultEmbeddingModel,
                int? numCtx,
                int? embeddingsNumCtx,
                int? maxStepsPerTurn,
                int? maxToolResultChars,
                int? maxFullMessages,
                string? keepAlive,
                string path)
            {
                if (isActiveGenericProvider)
                {
                    if (numCtx is null or < 512 or > 131072) // 131072 is qwen's max context.
                    {
                        throw new EngineConfigurationException(
                            $"Module '{portKey}' in '{path}' (resolved from generic_llm_provider) must set num_ctx to an integer between 512 and 131072.");
                    }
                }

                if (!isActiveGenericProvider && numCtx is not null)
                {
                    throw new EngineConfigurationException(
                        $"Module '{portKey}' in '{path}' must not set num_ctx (only the module resolved from generic_llm_provider may).");
                }

                if (!isActiveGenericEmbeddings && embeddingsNumCtx is not null)
                {
                    throw new EngineConfigurationException(
                        $"Module '{portKey}' in '{path}' must not set embeddings_num_ctx (only the module resolved from generic_embeddings may).");
                }

                if (isQwen)
                {
                    if (ollamaPort is null or < 1 or > 65535)
                    {
                        throw new EngineConfigurationException(
                            $"Module '{portKey}' in '{path}' (llm_provider_qwen) must set ollama_port to an integer between 1 and 65535.");
                    }

                    if (string.IsNullOrWhiteSpace(ollamaModel))
                    {
                        throw new EngineConfigurationException(
                            $"Module '{portKey}' in '{path}' (llm_provider_qwen) must set default_chat_model to a non-empty string.");
                    }
                }
                else
                {
                    if (!isActiveGenericEmbeddings && ollamaPort is not null)
                    {
                        throw new EngineConfigurationException(
                            $"Module '{portKey}' in '{path}' must not set ollama_port (only llm_provider_qwen or the module resolved from generic_embeddings may).");
                    }

                    if (!string.IsNullOrWhiteSpace(ollamaModel))
                    {
                        throw new EngineConfigurationException(
                            $"Module '{portKey}' in '{path}' must not set default_chat_model (only llm_provider_qwen may).");
                    }
                }

                if (isActiveGenericEmbeddings)
                {
                    if (ollamaPort is null or < 1 or > 65535)
                    {
                        throw new EngineConfigurationException(
                            $"Module '{portKey}' in '{path}' (resolved from generic_embeddings) must set ollama_port to an integer between 1 and 65535.");
                    }

                    if (string.IsNullOrWhiteSpace(defaultEmbeddingModel))
                    {
                        throw new EngineConfigurationException(
                            $"Module '{portKey}' in '{path}' (resolved from generic_embeddings) must set default_embedding_model to a non-empty string.");
                    }

                    if (string.IsNullOrWhiteSpace(keepAlive))
                    {
                        throw new EngineConfigurationException(
                            $"Module '{portKey}' in '{path}' (resolved from generic_embeddings) must set keep_model_loaded_for to a non-empty Ollama duration string.");
                    }

                    if (embeddingsNumCtx is null or < 256 or > 131072)
                    {
                        throw new EngineConfigurationException(
                            $"Module '{portKey}' in '{path}' (resolved from generic_embeddings) must set embeddings_num_ctx to an integer between 256 and 131072.");
                    }
                }
                else if (!string.IsNullOrWhiteSpace(defaultEmbeddingModel))
                {
                    throw new EngineConfigurationException(
                        $"Module '{portKey}' in '{path}' must not set default_embedding_model (only the module resolved from generic_embeddings may).");
                }

                if (isMemoryDirector)
                {
                    if (maxStepsPerTurn is null or < 1 or > 64)
                    {
                        throw new EngineConfigurationException(
                            $"Module '{portKey}' in '{path}' (memory_director) must set max_steps_per_turn to an integer between 1 and 64.");
                    }

                    if (maxToolResultChars is null or < 256 or > 131072)
                    {
                        throw new EngineConfigurationException(
                            $"Module '{portKey}' in '{path}' (memory_director) must set max_tool_result_chars to an integer between 256 and 131072.");
                    }

                    if (maxFullMessages is null or < 0 or > 200)
                    {
                        throw new EngineConfigurationException(
                            $"Module '{portKey}' in '{path}' (memory_director) must set max_full_messages to an integer between 0 and 200.");
                    }

                    if (string.IsNullOrWhiteSpace(keepAlive))
                    {
                        throw new EngineConfigurationException(
                            $"Module '{portKey}' in '{path}' (memory_director) must set keep_model_loaded_for to a non-empty Ollama duration string.");
                    }
                }
                else
                {
                    if (maxStepsPerTurn is not null
                        || maxToolResultChars is not null
                        || maxFullMessages is not null
                        || (!isActiveGenericEmbeddings && !string.IsNullOrWhiteSpace(keepAlive)))
                    {
                        throw new EngineConfigurationException(
                            $"Module '{portKey}' in '{path}' must not set memory_director options (only memory_director may).");
                    }
                }
            }

            // Structural roles the host always expects to find under modules[] and to treat as engine-mandatory.
            // required_by_engine on each row means "include in default startup"; it cannot by itself prove that a
            // router/director row exists if someone omitted that block from the file, so those identities stay fixed here.
            static void EnsureRequiredModulesPresent(
                List<EngineModuleInfo> list,
                string genericLlmProviderModuleKey,
                string genericDirectorModuleKey,
                string genericEmbeddingsModuleKey,
                string path)
            {
                void RequireCatalogEntryEngineMandatory(string portKey, string missingCatalogMessage)
                {
                    var module = list.FirstOrDefault(x =>
                        string.Equals(x.PortKey, portKey, StringComparison.OrdinalIgnoreCase));

                    if (module is null)
                    {
                        throw new EngineConfigurationException(missingCatalogMessage);
                    }

                    // Must match modules[].required_by_engine so defaults and structural requirements cannot disagree.
                    if (!module.RequiredByEngine)
                    {
                        throw new EngineConfigurationException(
                            $"Module '{portKey}' in '{path}' must set required_by_engine to true.");
                    }
                }

                RequireCatalogEntryEngineMandatory(
                    "router",
                    $"modules[] in '{path}' must include a router (port_key 'router').");

                RequireCatalogEntryEngineMandatory(
                    genericDirectorModuleKey,
                    $"modules[] in '{path}' must include the concrete generic_director module '{genericDirectorModuleKey}'.");

                RequireCatalogEntryEngineMandatory(
                    genericLlmProviderModuleKey,
                    $"modules[] in '{path}' must include the concrete generic_llm_provider module '{genericLlmProviderModuleKey}'.");

                RequireCatalogEntryEngineMandatory(
                    genericEmbeddingsModuleKey,
                    $"modules[] in '{path}' must include the concrete generic_embeddings module '{genericEmbeddingsModuleKey}'.");
            }

            static IReadOnlyList<EngineModuleInfo> MergeModules(
                List<ModuleDto> modulesDto,
                EnginePortMap portMap,
                string path,
                string genericLlmProviderModuleKey,
                string genericDirectorModuleKey,
                string genericEmbeddingsModuleKey)
            {
                var list = new List<EngineModuleInfo>();
                var seenLoadOrders = new HashSet<int>();
                foreach (var module in modulesDto)
                {
                    var portKey = module.PortKey?.Trim();
                    if (string.IsNullOrEmpty(portKey))
                    {
                        throw new EngineConfigurationException($"modules[] entry in '{path}' is missing port_key.");
                    }

                    // Port map is built directly from modules[].port (fail fast if a module is missing a port).
                    _ = portMap.GetRequiredPort(portKey);

                    if (module.LoadOrder is not int loadOrder)
                    {
                        throw new EngineConfigurationException($"Module '{portKey}' in '{path}' is missing load_order.");
                    }

                    if (loadOrder < 0)
                    {
                        throw new EngineConfigurationException($"Module '{portKey}' in '{path}' load_order must be >= 0 (got {loadOrder}).");
                    }

                    if (!seenLoadOrders.Add(loadOrder))
                    {
                        throw new EngineConfigurationException($"Duplicate load_order {loadOrder} in '{path}' (each module must have a unique load_order).");
                    }

                    // launch is a single string path per module; empty is invalid.
                    if (string.IsNullOrWhiteSpace(module.Launch))
                    {
                        throw new EngineConfigurationException($"Module '{portKey}' in '{path}' is missing launch.");
                    }

                    var launch = new EngineModuleLaunchInfo(module.Launch.Trim());
                    var endpoints = MergeEndpoints(module.Endpoints, portKey, path);
                    var isActiveGenericProvider = string.Equals(portKey, genericLlmProviderModuleKey, StringComparison.OrdinalIgnoreCase);
                    var isActiveGenericEmbeddings = string.Equals(portKey, genericEmbeddingsModuleKey, StringComparison.OrdinalIgnoreCase);
                    var isQwen = string.Equals(portKey, "llm_provider_qwen", StringComparison.OrdinalIgnoreCase);
                    var isMemoryDirector = string.Equals(portKey, "memory_director", StringComparison.OrdinalIgnoreCase);

                    ValidateModuleScopedOptions(
                        portKey,
                        isActiveGenericProvider,
                        isQwen,
                        isMemoryDirector,
                        isActiveGenericEmbeddings,
                        module.OllamaPort,
                        module.OllamaModel,
                        module.DefaultEmbeddingModel,
                        module.NumCtx,
                        module.EmbeddingsNumCtx,
                        module.MaxStepsPerTurn,
                        module.MaxToolResultChars,
                        module.MaxFullMessages,
                        module.KeepAlive,
                        path);

                    // Compose provider-agnostic options only for the active generic provider module.
                    var genericProviderOptions = isActiveGenericProvider
                        ? new GenericLlmProviderModuleOptions(module.NumCtx!.Value)
                        : null;

                    // Compose qwen options only for qwen modules.
                    var qwenOptions = isQwen
                        ? new QwenModuleOptions(module.OllamaPort!.Value, module.OllamaModel!.Trim())
                        : null;

                    var memoryDirectorOptions = isMemoryDirector
                        ? new MemoryDirectorModuleOptions(
                            module.MaxStepsPerTurn!.Value,
                            module.MaxToolResultChars!.Value,
                            module.MaxFullMessages!.Value,
                            module.KeepAlive!.Trim())
                        : null;

                    var embeddingsOptions = isActiveGenericEmbeddings
                        ? new EmbeddingsModuleOptions(
                            module.OllamaPort!.Value,
                            module.DefaultEmbeddingModel!.Trim(),
                            module.KeepAlive!.Trim(),
                            module.EmbeddingsNumCtx!.Value)
                        : null;

                    list.Add(new EngineModuleInfo(
                        portKey,
                        string.IsNullOrWhiteSpace(module.DisplayName) ? portKey : module.DisplayName.Trim(),
                        module.RequiredByEngine ?? true,
                        loadOrder,
                        launch,
                        endpoints,
                        genericProviderOptions,
                        qwenOptions,
                        memoryDirectorOptions,
                        embeddingsOptions));
                }

                if (list.Count == 0)
                {
                    throw new EngineConfigurationException($"No modules could be built from '{path}'.");
                }

                EnsureRequiredModulesPresent(list, genericLlmProviderModuleKey, genericDirectorModuleKey, genericEmbeddingsModuleKey, path);
                return list;
            }

            static void EnsureGenericLlmProviderModuleOptionsComplete(
                IReadOnlyList<EngineModuleInfo> modules,
                string genericLlmProviderModuleKey,
                string path)
            {
                var m = modules.FirstOrDefault(x =>
                    string.Equals(x.PortKey, genericLlmProviderModuleKey, StringComparison.OrdinalIgnoreCase));
                if (m is null)
                {
                    throw new EngineConfigurationException(
                        $"Internal error: generic_llm_provider module '{genericLlmProviderModuleKey}' missing after merge ('{path}').");
                }

                if (m.GenericLlmProviderOptions is null)
                {
                    throw new EngineConfigurationException(
                        $"Module '{genericLlmProviderModuleKey}' in '{path}' (resolved from generic_llm_provider) must have num_ctx (generic_llm_provider options).");
                }

                if (string.Equals(genericLlmProviderModuleKey, "llm_provider_qwen", StringComparison.OrdinalIgnoreCase))
                {
                    if (m.QwenOptions is null)
                    {
                        throw new EngineConfigurationException(
                            $"Module '{genericLlmProviderModuleKey}' in '{path}' must have qwen options (ollama_port, default_chat_model).");
                    }

                    if (m.QwenOptions.OllamaModel is not { } model || string.IsNullOrWhiteSpace(model))
                    {
                        throw new EngineConfigurationException(
                            $"generic_llm_provider ('{genericLlmProviderModuleKey}') default_chat_model missing or empty in '{path}'.");
                    }
                }
            }

            var repositoryRoot = FindRepositoryRoot();
            var path = repositoryRoot is null ? null : Path.Combine(repositoryRoot, "engine_config.json");
            if (repositoryRoot is null || path is null || !File.Exists(path))
            {
                throw new EngineConfigurationException(
                    "engine_config.json not found or repository root could not be resolved. Expected the file next to MorpheusEngine sources or under a discovered repo root.");
            }

            string json;
            try
            {
                json = File.ReadAllText(path);
            }
            catch (Exception e)
            {
                throw new EngineConfigurationException($"Failed to read engine_config.json at '{path}'.", e);
            }

            EngineConfigFileDto? dto;
            try
            {
                dto = JsonSerializer.Deserialize<EngineConfigFileDto>(json, _jsonOptions);
            }
            catch (JsonException e)
            {
                throw new EngineConfigurationException($"Invalid JSON in engine_config.json at '{path}'.", e);
            }

            if (dto?.Modules is null || dto.Modules.Count == 0)
            {
                throw new EngineConfigurationException($"engine_config.json at '{path}' must contain a non-empty 'modules' array.");
            }

            var moduleAliases = MergeModuleAliases(dto.ModuleAliases, path);
            var genericLlmProviderModuleKey = ResolveRequiredGenericProviderModuleKey(moduleAliases, path);
            var genericDirectorModuleKey = ResolveRequiredGenericDirectorModuleKey(moduleAliases, path);
            var genericEmbeddingsModuleKey = ResolveRequiredGenericEmbeddingsModuleKey(moduleAliases, path);
            var portMap = BuildPortMapFromModules(dto.Modules, path);
            var modules = MergeModules(dto.Modules, portMap, path, genericLlmProviderModuleKey, genericDirectorModuleKey, genericEmbeddingsModuleKey);
            EnsureGenericLlmProviderModuleOptionsComplete(modules, genericLlmProviderModuleKey, path);
            var turnPipelines = MergeTurnPipelines(dto.TurnPipelines, path);
            ValidateTurnPipelines(turnPipelines, modules, moduleAliases, path);

            return new EngineConfiguration(repositoryRoot, portMap, modules, moduleAliases, turnPipelines);
        }

        if (_cached is not null)
        {
            return _cached;
        }

        lock (Sync) // Ensures a single thread populates _cached after the null check above (double-checked locking).
        {
            return _cached ??= LoadConfigurationUncached();
        }
    }

    public static EnginePortMap GetPorts() => GetConfiguration().PortMap;
    #endregion

    #region Helpers
    public static string? FindRepositoryRoot()
    {
        return FindRepositoryRoot(new DirectoryInfo(AppContext.BaseDirectory))
            ?? FindRepositoryRoot(new DirectoryInfo(Environment.CurrentDirectory));
    }

    private static string? FindRepositoryRoot(DirectoryInfo? start)
    {
        for (var dir = start; dir is not null; dir = dir.Parent)
        {
            if (File.Exists(Path.Combine(dir.FullName, "engine_config.json")))
            {
                return dir.FullName;
            }

            if (File.Exists(Path.Combine(dir.FullName, "dotnet", "MorpheusEngine.sln")))
            {
                return dir.FullName;
            }

            if (File.Exists(Path.Combine(dir.FullName, "MorpheusEngine.sln")))
            {
                return dir.Parent?.FullName ?? dir.FullName;
            }
        }

        return null;
    }
    #endregion
}
