using System.Text.Json;
using System.Text.Json.Serialization;

namespace MorpheusEngine;

// Note: sealing private records is the desired default: it doesn't change affect the open-closed principle while ruling out some potential autogenerated equality comparator bugs.

/// <summary>Thrown when engine_config.json is missing, invalid, or violates the engine contract (fail fast; no silent fallbacks).</summary>
public sealed class EngineConfigurationException : Exception
{
    public EngineConfigurationException(string message)
        : base(message)
    {
    }

    public EngineConfigurationException(string message, Exception innerException)
        : base(message, innerException)
    {
    }
}

/// <summary>Maps each module port_key to its TCP listen port.</summary>
public sealed class EnginePortMap
{
    private readonly IReadOnlyDictionary<string, int> _mapping; // Port identifier to int: example: "router" -> 1234

    /// <summary>Keys that must appear under JSON ports (and must not include extra keys).</summary>
    public static readonly string[] RequiredPortKeys = ["router", "generic_llm_provider", "director", "session_store"];
    /// <summary>Set of <see cref="RequiredPortKeys"/> for fast membership checks (case-insensitive).</summary>
    public static readonly HashSet<string> RequiredPortKeySet = new(RequiredPortKeys, StringComparer.OrdinalIgnoreCase);

    // Constructor restricted to this project only.
    internal EnginePortMap(IReadOnlyDictionary<string, int> mapping)
    {
        _mapping = mapping;
    }

    /// <summary>Returns the configured listen port for a known module <paramref name="portKey"/>.</summary>
    /// <exception cref="EngineConfigurationException">Unknown <paramref name="portKey"/>.</exception>
    public int GetRequiredPort(string portKey) // portKey example: "router", resolves to int.
    {
        if (!_mapping.TryGetValue(portKey, out var port))
        {
            throw new EngineConfigurationException(
                $"Unknown port_key '{portKey}' for listen port lookup. Known keys: {string.Join(", ", RequiredPortKeys)}.");
        }

        return port;
    }

    /// <summary>Whether <paramref name="portKey"/> has a listen port entry (used when validating module rows).</summary>
    public bool HasListenPortForModule(string portKey) => _mapping.ContainsKey(portKey);
}

/// <summary>Launch metadata for a module process.</summary>
/// <param name="Artifact">Path to the built executable (often under bin/Debug/...), relative to the repository root unless absolute.</param>
public sealed record EngineModuleLaunchInfo(string Artifact);

/// <summary>One HTTP endpoint exposed by a module.</summary>
/// <param name="Path">URL path on that module, e.g. /health or /intent.</param>
/// <param name="Description">Short label; used by the WPF UI when listing endpoints (see MainWindow).</param>
/// <param name="Method">GET or POST (required in JSON).</param>
/// <param name="RequestContract">Optional logical name for the request body shape (e.g. turn_request); drives sample templates.</param>
/// <param name="BodyTemplate">Optional JSON string template; if omitted, filled from <see cref="EngineContractExamples"/> when <paramref name="RequestContract"/> is set.</param>
public sealed record EngineEndpointInfo(
    string Path, // example: /health, /intent
    string? Description, // Used by MainWindow for combo box / endpoint labels.
    string Method,
    string? RequestContract, // Logical contract id for request JSON shape / examples.
    string? BodyTemplate); // Templates are optional overrides / snippets; contracts stay string ids for JSON flexibility.

/// <summary>Options required by whichever concrete module is mapped from generic_llm_provider.</summary>
public sealed record GenericLlmProviderModuleOptions(
    int NumCtx,
    string WarmupGameProjectId);

/// <summary>Options specific to the llm_provider_qwen module implementation.</summary>
public sealed record QwenModuleOptions(
    int OllamaPort,
    string OllamaModel);

public sealed record EngineModuleInfo(
    string PortKey, // stable module id (e.g. router); actual port is in EngineConfiguration.PortMap.
    string DisplayName, // Shown in UI / logs;
    bool Required,
    EngineModuleLaunchInfo LaunchInfo,
    IReadOnlyList<EngineEndpointInfo> Endpoints,
    /// <summary>Set only on the module resolved from generic_llm_provider.</summary>
    GenericLlmProviderModuleOptions? GenericLlmProviderOptions = null,
    /// <summary>Set only on llm_provider_qwen.</summary>
    QwenModuleOptions? QwenOptions = null);

/// <summary>Loaded engine configuration: repository layout, listen ports, module list, proxy aliases, and module-derived settings from generic provider + qwen-specific options.</summary>
public sealed class EngineConfiguration
{
    /// <summary>Repository root containing engine_config.json and typically a dotnet folder.</summary>
    // Q: what's this used for? — Resolving relative artifact paths and choosing the dotnet working directory.
    public string RepositoryRoot { get; }

    public EnginePortMap PortMap { get; }

    public IReadOnlyList<EngineModuleInfo> ModulesInfos { get; }

    // Used to make http messages mention only the generic modules instead of having to rely on specific implementation modules. Ex: llm_provider_qwen becomes just generic_llm_provider and the Router resolves it back to llm_provider_qwen or whichever generic llm module is currently used.
    public IReadOnlyDictionary<string, string> ModuleAliases { get; }

    /// <summary>From the llm_provider_qwen module's ollama_port in JSON.</summary>
    public int LlmProviderOllamaListenPort { get; } // Note: I'm not convinced by implementation mentions in this generic class.

    /// <summary>From the llm_provider_qwen module's default_chat_model in JSON (Ollama model for /api/chat and /api/generate).</summary>
    public string LlmProviderOllamaModel { get; }

    /// <summary>From the generic_llm_provider module's num_ctx in JSON (forwarded as Ollama options.num_ctx in qwen).</summary>
    public int LlmProviderNumCtx { get; }

    /// <summary>From the generic_llm_provider module's warmup_game_project_id in JSON.</summary>
    public string LlmProviderWarmupGameProjectId { get; }

    public EngineConfiguration(
        string repositoryRoot,
        EnginePortMap portMap,
        IReadOnlyList<EngineModuleInfo> modulesInfos,
        IReadOnlyDictionary<string, string> moduleAliases,
        int llmProviderOllamaListenPort,
        string llmProviderOllamaModel,
        int llmProviderNumCtx,
        string llmProviderWarmupGameProjectId)
    {
        RepositoryRoot = repositoryRoot;
        PortMap = portMap;
        ModulesInfos = modulesInfos;
        ModuleAliases = moduleAliases;
        LlmProviderOllamaListenPort = llmProviderOllamaListenPort;
        LlmProviderOllamaModel = llmProviderOllamaModel;
        LlmProviderNumCtx = llmProviderNumCtx;
        LlmProviderWarmupGameProjectId = llmProviderWarmupGameProjectId;
    }

    /// <summary>
    /// Resolves a logical proxy target (e.g. generic_llm_provider) to a configured port_key before module lookup.
    /// Keys that are already real port_key values pass through unchanged (not an error—no log spam).
    /// </summary>
    public string ResolveProxyTargetModuleKey(string logicalKey)
    {
        if (string.IsNullOrWhiteSpace(logicalKey))
        {
            return logicalKey;
        }

        return ModuleAliases.TryGetValue(logicalKey, out var mapped) && !string.IsNullOrWhiteSpace(mapped)
            ? mapped.Trim()
            : logicalKey;
    }

    /// <inheritdoc cref="EnginePortMap.GetRequiredPort"/>
    public int GetRequiredListenPort(string portKey)
    {
        if (PortMap.HasListenPortForModule(portKey))
        {
            return PortMap.GetRequiredPort(portKey);
        }

        // Support concrete module keys that are targeted by a logical alias in ports (e.g. generic_llm_provider -> llm_provider_qwen).
        foreach (var alias in ModuleAliases)
        {
            if (string.Equals(alias.Value, portKey, StringComparison.OrdinalIgnoreCase)
                && PortMap.HasListenPortForModule(alias.Key))
            {
                return PortMap.GetRequiredPort(alias.Key);
            }
        }

        return PortMap.GetRequiredPort(portKey);
    }

    /// <summary>
    /// Prefer this over a property: path is derived from <see cref="RepositoryRoot"/> and directory existence.
    /// Example: repository C:\MorpheusEngine with a dotnet subfolder → C:\MorpheusEngine\dotnet;
    /// if dotnet is missing (non-standard layout) → falls back to <see cref="RepositoryRoot"/>.
    /// </summary>
    // Q: in what conditions would dotnetRoot not exist? — Sparse checkouts or running with config at repo root without a dotnet subdir.
    public string GetDotnetRoot()
    {
        var dotnetRoot = Path.Combine(RepositoryRoot, "dotnet");
        return Directory.Exists(dotnetRoot) ? dotnetRoot : RepositoryRoot;
    }

    public EngineModuleInfo? FindModule(string portKey)
    {
        foreach (var module in ModulesInfos)
        {
            if (string.Equals(module.PortKey, portKey, StringComparison.OrdinalIgnoreCase))
            {
                return module;
            }
        }

        return null;
    }

    /// <summary>Finds which module is bound to the given TCP <paramref name="port"/> (listen ports from <see cref="PortMap"/>).</summary>
    public EngineModuleInfo? GetModuleForListeningPort(int port)
    {
        foreach (var module in ModulesInfos)
        {
            if (GetRequiredListenPort(module.PortKey) == port)
            {
                return module;
            }
        }

        return null;
    }

    public EngineEndpointInfo? FindEndpointForPort(int port, string path)
    {
        var normalized = NormalizePath(path);
        var module = GetModuleForListeningPort(port);
        if (module is null)
        {
            return null; // Acceptable to return null in this case: indicates failure to find endpoint.
        }

        foreach (var endpoint in module.Endpoints)
        {
            if (string.Equals(NormalizePath(endpoint.Path), normalized, StringComparison.OrdinalIgnoreCase))
            {
                return endpoint;
            }
        }

        return null;
    }

    public static string NormalizePath(string path)
    {
        if (string.IsNullOrWhiteSpace(path))
        {
            return "/";
        }

        var trimmed = path.Trim();
        return trimmed.StartsWith('/') ? trimmed : "/" + trimmed;
    }
}

// Note: public static class in C# forces a singleton like behaviour.
public static class EngineConfigLoader
{
    #region Nested types
    // DTO: Data transfer object: JSON deserialization shape, not the runtime EngineConfiguration model.

    private sealed class EngineConfigFileDto
    {
        public List<ModuleDto>? Modules { get; set; }

        [JsonPropertyName("module_aliases")]
        public Dictionary<string, string>? ModuleAliases { get; set; }
    }

    private sealed class ModuleDto
    {
        [JsonPropertyName("port_key")]
        public string? PortKey { get; set; }

        [JsonPropertyName("display_name")]
        public string? DisplayName { get; set; }

        public bool? Required { get; set; }
        public ModuleLaunchDto? Launch { get; set; }
        public List<EndpointDto>? Endpoints { get; set; }

        [JsonPropertyName("ollama_port")]
        public int? OllamaPort { get; set; }

        [JsonPropertyName("default_chat_model")]
        public string? OllamaModel { get; set; }

        [JsonPropertyName("num_ctx")]
        public int? NumCtx { get; set; }

        [JsonPropertyName("warmup_game_project_id")]
        public string? WarmupGameProjectId { get; set; }
    }

    private sealed class ModuleLaunchDto
    {
        public string? Artifact { get; set; }

        [JsonExtensionData]
        public Dictionary<string, JsonElement>? AdditionalFields { get; set; }
    }

    private sealed class EndpointDto
    {
        // Q: why no JsonPropertyName()'s here? — Names match JSON camelCase defaults with PropertyNameCaseInsensitive on serializer.
        public string? Path { get; set; }
        public string? Description { get; set; }
        public string? Method { get; set; }

        [JsonPropertyName("request_contract")]
        public string? RequestContract { get; set; }

        [JsonPropertyName("body_template")]
        public string? BodyTemplate { get; set; }
    }
    #endregion

    #region Private data
    private static readonly JsonSerializerOptions _jsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        ReadCommentHandling = JsonCommentHandling.Skip,
        AllowTrailingCommas = true
    };

    private static EngineConfiguration? _cached;

    /// <summary>Protects double-checked initialization of <see cref="_cached"/> together with <see cref="GetConfiguration"/>.</summary>
    // Mutex for the cache: only one thread runs <see cref="LoadConfigurationUncached"/> when cache is cold.
    private static readonly object Sync = new();

    private static IReadOnlyDictionary<string, string> DefaultModuleAliases() =>
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["generic_llm_provider"] = "llm_provider_qwen"
        };
    #endregion

    #region Public methods
    public static EngineConfiguration GetConfiguration()
    {
        if (_cached is not null)
        {
            return _cached;
        }

        lock (Sync) // Ensures a single thread populates _cached after the null check above (double-checked locking).
        {
            return _cached ??= LoadConfigurationUncached();
        }
    }

    public static EnginePortMap GetPorts() => GetConfiguration().PortMap;
    #endregion

    #region Private methods
    private static EngineConfiguration LoadConfigurationUncached()
    {
        var repositoryRoot = FindRepositoryRoot();
        var path = repositoryRoot is null ? null : Path.Combine(repositoryRoot, "engine_config.json");
        if (repositoryRoot is null || path is null || !File.Exists(path))
        {
            throw new EngineConfigurationException(
                "engine_config.json not found or repository root could not be resolved. Expected the file next to MorpheusEngine sources or under a discovered repo root.");
        }

        string json;
        try
        {
            json = File.ReadAllText(path);
        }
        catch (Exception e)
        {
            throw new EngineConfigurationException($"Failed to read engine_config.json at '{path}'.", e);
        }

        using var doc = JsonDocument.Parse(json, new JsonDocumentOptions { CommentHandling = JsonCommentHandling.Skip });
        var root = doc.RootElement;
        if (!root.TryGetProperty("ports", out var portsElement))
        {
            throw new EngineConfigurationException($"engine_config.json at '{path}' must contain a top-level 'ports' object.");
        }

        var portMap = BuildPortMapFromJson(portsElement, path);

        EngineConfigFileDto? dto;
        try
        {
            dto = JsonSerializer.Deserialize<EngineConfigFileDto>(json, _jsonOptions);
        }
        catch (JsonException e)
        {
            throw new EngineConfigurationException($"Invalid JSON in engine_config.json at '{path}'.", e);
        }

        if (dto?.Modules is null || dto.Modules.Count == 0)
        {
            throw new EngineConfigurationException($"engine_config.json at '{path}' must contain a non-empty 'modules' array.");
        }

        var moduleAliases = MergeModuleAliases(dto.ModuleAliases, path);
        var genericLlmProviderModuleKey = ResolveRequiredGenericProviderModuleKey(moduleAliases, path);
        var modules = MergeModules(dto.Modules, portMap, path, genericLlmProviderModuleKey, moduleAliases);
        var ollamaPort = RequireLlmProviderOllamaPort(modules, genericLlmProviderModuleKey, path);
        var ollamaModel = RequireLlmProviderOllamaModel(modules, genericLlmProviderModuleKey, path);
        var qwenNumCtx = RequireLlmProviderNumCtx(modules, genericLlmProviderModuleKey, path);
        var qwenWarmupGameProjectId = RequireLlmProviderWarmupGameProjectId(modules, genericLlmProviderModuleKey, path);

        return new EngineConfiguration(
            repositoryRoot,
            portMap,
            modules,
            moduleAliases,
            ollamaPort,
            ollamaModel,
            qwenNumCtx,
            qwenWarmupGameProjectId);
    }

    /// <summary>Intentional single call site: kept extracted so <see cref="LoadConfigurationUncached"/> stays readable (CodingStyle documented exception).</summary>
    private static EnginePortMap BuildPortMapFromJson(JsonElement portsEl, string configPath)
    {
        if (portsEl.ValueKind != JsonValueKind.Object)
        {
            throw new EngineConfigurationException($"'ports' in '{configPath}' must be a JSON object.");
        }

        var dict = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
        foreach (var prop in portsEl.EnumerateObject())
        {
            var key = prop.Name.Trim();
            if (!EnginePortMap.RequiredPortKeySet.Contains(key))
            {
                throw new EngineConfigurationException(
                    $"ports: unknown key '{prop.Name}' in '{configPath}'. Allowed keys only: {string.Join(", ", EnginePortMap.RequiredPortKeys)}.");
            }

            if (prop.Value.ValueKind != JsonValueKind.Number || !prop.Value.TryGetInt32(out var port))
            {
                throw new EngineConfigurationException($"ports.{prop.Name} in '{configPath}' must be an integer TCP port.");
            }

            if (port is < 1 or > 65535)
            {
                throw new EngineConfigurationException($"ports.{prop.Name} in '{configPath}' must be between 1 and 65535 (got {port}).");
            }

            dict[key] = port;
        }

        foreach (var required in EnginePortMap.RequiredPortKeys)
        {
            if (!dict.ContainsKey(required))
            {
                throw new EngineConfigurationException(
                    $"ports in '{configPath}' must include '{required}'. Present: {string.Join(", ", dict.Keys)}.");
            }
        }

        return new EnginePortMap(dict);
    }

    /// <summary>Intentional single call site: kept extracted for readability (CodingStyle documented exception).</summary>
    private static IReadOnlyList<EngineModuleInfo> MergeModules(
        List<ModuleDto> modulesDto,
        EnginePortMap portMap,
        string path,
        string genericLlmProviderModuleKey,
        IReadOnlyDictionary<string, string> moduleAliases)
    {
        var list = new List<EngineModuleInfo>();
        foreach (var module in modulesDto)
        {
            var portKey = module.PortKey?.Trim();
            if (string.IsNullOrEmpty(portKey))
            {
                throw new EngineConfigurationException($"modules[] entry in '{path}' is missing port_key.");
            }

            if (!HasListenPortForModuleOrAlias(portMap, moduleAliases, portKey))
            {
                throw new EngineConfigurationException(
                    $"Module '{portKey}' in '{path}' has no matching entry under ports (directly or through module_aliases). Known required port keys: {string.Join(", ", EnginePortMap.RequiredPortKeys)}.");
            }

            var launch = MergeLaunch(module.Launch, portKey, path);
            var endpoints = MergeEndpoints(module.Endpoints, portKey, path);
            var isActiveGenericProvider = string.Equals(portKey, genericLlmProviderModuleKey, StringComparison.OrdinalIgnoreCase);
            var isQwen = string.Equals(portKey, "llm_provider_qwen", StringComparison.OrdinalIgnoreCase);

            ValidateModuleScopedOptions(
                portKey,
                isActiveGenericProvider,
                isQwen,
                module.OllamaPort,
                module.OllamaModel,
                module.NumCtx,
                module.WarmupGameProjectId,
                path);

            // Compose provider-agnostic options only for the active generic provider module.
            var genericProviderOptions = isActiveGenericProvider
                ? new GenericLlmProviderModuleOptions(module.NumCtx!.Value, module.WarmupGameProjectId!.Trim())
                : null;

            // Compose qwen options only for qwen modules.
            var qwenOptions = isQwen
                ? new QwenModuleOptions(module.OllamaPort!.Value, module.OllamaModel!.Trim())
                : null;

            list.Add(new EngineModuleInfo(
                portKey,
                string.IsNullOrWhiteSpace(module.DisplayName) ? portKey : module.DisplayName.Trim(),
                module.Required ?? true,
                launch,
                endpoints,
                genericProviderOptions,
                qwenOptions));
        }

        if (list.Count == 0)
        {
            throw new EngineConfigurationException($"No modules could be built from '{path}'.");
        }

        EnsureRequiredModulesPresent(list, genericLlmProviderModuleKey, path);
        return list;
    }

    private static void ValidateModuleScopedOptions(
        string portKey,
        bool isActiveGenericProvider,
        bool isQwen,
        int? ollamaPort,
        string? ollamaModel,
        int? numCtx,
        string? warmupGameProjectId,
        string path)
    {
        if (isActiveGenericProvider)
        {
            if (numCtx is null or < 512 or > 131072)
            {
                throw new EngineConfigurationException(
                    $"Module '{portKey}' in '{path}' (resolved from generic_llm_provider) must set num_ctx to an integer between 512 and 131072.");
            }

            if (string.IsNullOrWhiteSpace(warmupGameProjectId))
            {
                throw new EngineConfigurationException(
                    $"Module '{portKey}' in '{path}' (resolved from generic_llm_provider) must set warmup_game_project_id to a non-empty string.");
            }
        }

        if (!isActiveGenericProvider && numCtx is not null)
        {
            throw new EngineConfigurationException(
                $"Module '{portKey}' in '{path}' must not set num_ctx (only the module resolved from generic_llm_provider may).");
        }

        if (!isActiveGenericProvider && !string.IsNullOrWhiteSpace(warmupGameProjectId))
        {
            throw new EngineConfigurationException(
                $"Module '{portKey}' in '{path}' must not set warmup_game_project_id (only the module resolved from generic_llm_provider may).");
        }

        if (isQwen)
        {
            if (ollamaPort is null or < 1 or > 65535)
            {
                throw new EngineConfigurationException(
                    $"Module '{portKey}' in '{path}' (llm_provider_qwen) must set ollama_port to an integer between 1 and 65535.");
            }

            if (string.IsNullOrWhiteSpace(ollamaModel))
            {
                throw new EngineConfigurationException(
                    $"Module '{portKey}' in '{path}' (llm_provider_qwen) must set default_chat_model to a non-empty string.");
            }
        }
        else
        {
            if (ollamaPort is not null)
            {
                throw new EngineConfigurationException(
                    $"Module '{portKey}' in '{path}' must not set ollama_port (only llm_provider_qwen may).");
            }

            if (!string.IsNullOrWhiteSpace(ollamaModel))
            {
                throw new EngineConfigurationException(
                    $"Module '{portKey}' in '{path}' must not set default_chat_model (only llm_provider_qwen may).");
            }
        }

    }

    private static void EnsureRequiredModulesPresent(List<EngineModuleInfo> list, string genericLlmProviderModuleKey, string path)
    {
        static bool Has(List<EngineModuleInfo> m, string key) =>
            m.Exists(x => string.Equals(x.PortKey, key, StringComparison.OrdinalIgnoreCase));

        if (!Has(list, "router")
            || !Has(list, genericLlmProviderModuleKey)
            || !Has(list, "intent_extractor")
            || !Has(list, "director")
            || !Has(list, "session_store"))
        {
            throw new EngineConfigurationException(
                $"modules in '{path}' must include router, intent_extractor, director, session_store, and the concrete module mapped from generic_llm_provider ('{genericLlmProviderModuleKey}').");
        }
    }

    private static int RequireLlmProviderOllamaPort(IReadOnlyList<EngineModuleInfo> modules, string providerPortKey, string path)
    {
        if (!string.Equals(providerPortKey, "llm_provider_qwen", StringComparison.OrdinalIgnoreCase))
        {
            throw new EngineConfigurationException(
                $"generic_llm_provider is mapped to '{providerPortKey}' in '{path}', but EngineConfiguration currently expects llm_provider_qwen-specific ollama_port.");
        }

        var m = modules.FirstOrDefault(x => string.Equals(x.PortKey, providerPortKey, StringComparison.OrdinalIgnoreCase));
        if (m?.QwenOptions?.OllamaPort is not int p)
        {
            throw new EngineConfigurationException($"generic_llm_provider ('{providerPortKey}') ollama_port missing or invalid in '{path}'.");
        }
        return p;
    }

    private static string RequireLlmProviderOllamaModel(IReadOnlyList<EngineModuleInfo> modules, string providerPortKey, string path)
    {
        if (!string.Equals(providerPortKey, "llm_provider_qwen", StringComparison.OrdinalIgnoreCase))
        {
            throw new EngineConfigurationException(
                $"generic_llm_provider is mapped to '{providerPortKey}' in '{path}', but EngineConfiguration currently expects llm_provider_qwen-specific default_chat_model.");
        }

        var m = modules.FirstOrDefault(x => string.Equals(x.PortKey, providerPortKey, StringComparison.OrdinalIgnoreCase));
        if (m?.QwenOptions?.OllamaModel is not { } model || string.IsNullOrWhiteSpace(model))
        {
            throw new EngineConfigurationException($"generic_llm_provider ('{providerPortKey}') default_chat_model missing or empty in '{path}'.");
        }
        return model;
    }

    private static int RequireLlmProviderNumCtx(IReadOnlyList<EngineModuleInfo> modules, string providerPortKey, string path)
    {
        var m = modules.FirstOrDefault(x => string.Equals(x.PortKey, providerPortKey, StringComparison.OrdinalIgnoreCase));
        if (m?.GenericLlmProviderOptions?.NumCtx is not int numCtx)
        {
            throw new EngineConfigurationException($"generic_llm_provider ('{providerPortKey}') num_ctx missing or invalid in '{path}'.");
        }
        return numCtx;
    }

    private static string RequireLlmProviderWarmupGameProjectId(IReadOnlyList<EngineModuleInfo> modules, string providerPortKey, string path)
    {
        var m = modules.FirstOrDefault(x => string.Equals(x.PortKey, providerPortKey, StringComparison.OrdinalIgnoreCase));
        if (m?.GenericLlmProviderOptions?.WarmupGameProjectId is not { } id || string.IsNullOrWhiteSpace(id))
        {
            throw new EngineConfigurationException(
                $"generic_llm_provider ('{providerPortKey}') warmup_game_project_id missing or empty in '{path}' (required for Ollama narration warm-up).");
        }

        var trimmed = id.Trim();
        if (trimmed.Contains("..", StringComparison.Ordinal)
            || trimmed.Contains('/', StringComparison.Ordinal)
            || trimmed.Contains('\\', StringComparison.Ordinal))
        {
            throw new EngineConfigurationException(
                $"generic_llm_provider ('{providerPortKey}') warmup_game_project_id in '{path}' must not contain path separators or '..'.");
        }

        return trimmed;
    }

    private static string ResolveRequiredGenericProviderModuleKey(
        IReadOnlyDictionary<string, string> moduleAliases,
        string path)
    {
        if (!moduleAliases.TryGetValue("generic_llm_provider", out var mapped) || string.IsNullOrWhiteSpace(mapped))
        {
            throw new EngineConfigurationException(
                $"module_aliases in '{path}' must map 'generic_llm_provider' to a concrete module key.");
        }

        var providerPortKey = mapped.Trim();
        if (!EnginePortMap.RequiredPortKeySet.Contains("generic_llm_provider"))
        {
            throw new EngineConfigurationException("Internal error: generic_llm_provider must be part of required port keys.");
        }

        return providerPortKey;
    }

    private static bool HasListenPortForModuleOrAlias(
        EnginePortMap portMap,
        IReadOnlyDictionary<string, string> moduleAliases,
        string modulePortKey)
    {
        if (portMap.HasListenPortForModule(modulePortKey))
        {
            return true;
        }

        foreach (var alias in moduleAliases)
        {
            if (string.Equals(alias.Value, modulePortKey, StringComparison.OrdinalIgnoreCase)
                && portMap.HasListenPortForModule(alias.Key))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>Intentional single call site: kept extracted for readability (CodingStyle documented exception).</summary>
    private static EngineModuleLaunchInfo MergeLaunch(ModuleLaunchDto? launch, string portKey, string path)
    {
        if (launch is null || string.IsNullOrWhiteSpace(launch.Artifact))
        {
            throw new EngineConfigurationException($"Module '{portKey}' in '{path}' is missing launch.artifact.");
        }

        // Legacy config was allowed to specify launch.dev_project for MORPHEUS_DEV_LAUNCH.
        // Executable-only launch is now enforced, so this is a hard config error.
        if (launch.AdditionalFields is not null
            && launch.AdditionalFields.Keys.Any(k => string.Equals(k, "dev_project", StringComparison.OrdinalIgnoreCase)))
        {
            throw new EngineConfigurationException(
                $"Module '{portKey}' in '{path}' must not set launch.dev_project. Engine now launches modules from built artifacts only (launch.artifact).");
        }

        return new EngineModuleLaunchInfo(launch.Artifact.Trim());
    }

    /// <summary>Intentional single call site: kept extracted for readability (CodingStyle documented exception).</summary>
    private static IReadOnlyList<EngineEndpointInfo> MergeEndpoints(List<EndpointDto>? endpointsDto, string modulePortKey, string path)
    {
        if (endpointsDto is null)
        {
            throw new EngineConfigurationException($"Module '{modulePortKey}' in '{path}' must declare an endpoints array.");
        }

        var list = new List<EngineEndpointInfo>();
        foreach (var endpoint in endpointsDto)
        {
            var epPath = endpoint.Path?.Trim();
            if (string.IsNullOrEmpty(epPath))
            {
                throw new EngineConfigurationException(
                    $"Module '{modulePortKey}' in '{path}' has an endpoint with missing or empty path.");
            }

            if (string.IsNullOrWhiteSpace(endpoint.Method))
            {
                throw new EngineConfigurationException(
                    $"Module '{modulePortKey}' endpoint '{epPath}' in '{path}' must declare method (GET or POST).");
            }

            var method = endpoint.Method.Trim().ToUpperInvariant();
            if (method is not ("GET" or "POST"))
            {
                throw new EngineConfigurationException(
                    $"Module '{modulePortKey}' endpoint '{epPath}' in '{path}' has invalid method '{endpoint.Method}' (expected GET or POST).");
            }

            var requestContract = string.IsNullOrWhiteSpace(endpoint.RequestContract)
                ? null
                : endpoint.RequestContract.Trim();

            list.Add(new EngineEndpointInfo(
                EngineConfiguration.NormalizePath(epPath),
                string.IsNullOrWhiteSpace(endpoint.Description) ? null : endpoint.Description.Trim(),
                method,
                requestContract,
                string.IsNullOrWhiteSpace(endpoint.BodyTemplate)
                    ? EngineContractExamples.TryGetRequestBodyTemplate(requestContract)
                    : endpoint.BodyTemplate));
        }

        return list;
    }

    private static IReadOnlyDictionary<string, string> MergeModuleAliases(Dictionary<string, string>? fromFile, string path)
    {
        var merged = new Dictionary<string, string>(DefaultModuleAliases(), StringComparer.OrdinalIgnoreCase);
        if (fromFile is not null)
        {
            foreach (var pair in fromFile)
            {
                if (string.IsNullOrWhiteSpace(pair.Key) || string.IsNullOrWhiteSpace(pair.Value))
                {
                    throw new EngineConfigurationException(
                        $"module_aliases in '{path}' contains an entry with empty key or value.");
                }

                merged[pair.Key.Trim()] = pair.Value.Trim();
            }
        }

        return merged;
    }
    #endregion

    #region Helpers
    public static string? FindRepositoryRoot()
    {
        return FindRepositoryRoot(new DirectoryInfo(AppContext.BaseDirectory))
            ?? FindRepositoryRoot(new DirectoryInfo(Environment.CurrentDirectory));
    }

    private static string? FindRepositoryRoot(DirectoryInfo? start)
    {
        for (var dir = start; dir is not null; dir = dir.Parent)
        {
            if (File.Exists(Path.Combine(dir.FullName, "engine_config.json")))
            {
                return dir.FullName;
            }

            if (File.Exists(Path.Combine(dir.FullName, "dotnet", "MorpheusEngine.sln")))
            {
                return dir.FullName;
            }

            if (File.Exists(Path.Combine(dir.FullName, "MorpheusEngine.sln")))
            {
                return dir.Parent?.FullName ?? dir.FullName;
            }
        }

        return null;
    }
    #endregion
}
